---
  - hosts: elasticsearch
    remote_user: ubuntu
    become: yes
    become_method: sudo
    tasks: 
      - name: add java repo
        apt_repository: repo='ppa:webupd8team/java'
      - name: auto accept oracle jdk license
        shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
      - name: install java
        apt: 
          name: oracle-java8-installer
          update_cache: yes
      - name: download es
        get_url:
          url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.3.2.deb
          dest: /home/ubuntu/es.deb
      - name: install es
        apt: deb=/home/ubuntu/es.deb
      - name: start es
        service: name=elasticsearch state=restarted
      - name: copy config file
        copy: 
          src: /home/ubuntu/directdemo2/config/elasticsearch.yml
          dest: /etc/elasticsearch/
      - name: install mongo connector
        apt: name={{ item }} state=present update_cache=yes
        with_items:
          - python3
          - python3-setuptools
          - python3-dev
          - build-essential
      - name: install pip
        easy_install: 
          name: pip
          state: present
          executable: /usr/bin/easy_install3
      - name: install mongoconnector
        pip:
          name: mongo-connector[elastic5]
          state: present

